#!/usr/bin/env python3
from pathlib import Path
import ast
import re
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
FONT_PATH = Path('/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc')
FONT_INDEX = 0  # Noto Sans CJK JP
BASE_SIZE = 64
CELL_W = 72
CELL_H = 80
BASELINE_Y = 58
ORIGIN_X = 4
COLS = 20

chars = set(chr(i) for i in range(32, 127))
for p in ROOT.rglob('*.gd'):
    text = p.read_text(encoding='utf-8')
    for m in re.finditer(r'"(?:\\.|[^"\\])*"', text):
        try:
            value = ast.literal_eval(m.group(0))
        except Exception:
            continue
        chars.update(value)
chars.discard('\n')
chars.discard('\r')
chars.discard('\t')
chars = sorted(chars, key=ord)

font = ImageFont.truetype(str(FONT_PATH), BASE_SIZE, index=FONT_INDEX)
rows = (len(chars) + COLS - 1) // COLS
atlas = Image.new('RGBA', (COLS * CELL_W, rows * CELL_H), (255, 255, 255, 0))
draw = ImageDraw.Draw(atlas)
advances = []
for i, ch in enumerate(chars):
    x = (i % COLS) * CELL_W
    y = (i // COLS) * CELL_H
    draw.text((x + ORIGIN_X, y + BASELINE_Y), ch, font=font, fill=(255, 255, 255, 255), anchor='ls')
    advances.append(float(font.getlength(ch)))

atlas_path = ROOT / 'assets' / 'ui_font_atlas.png'
atlas.save(atlas_path, optimize=True)

codepoints = ', '.join(str(ord(c)) for c in chars)
advance_text = ', '.join(f'{a:.4f}' for a in advances)
data = f'''# Generated by tools/build_ui_font_atlas.py.
# The project ships only a raster glyph atlas, not the source font file.
extends RefCounted

const BASE_SIZE := {BASE_SIZE}
const CELL_W := {CELL_W}
const CELL_H := {CELL_H}
const BASELINE_Y := {BASELINE_Y}
const ORIGIN_X := {ORIGIN_X}
const COLS := {COLS}
const CODEPOINTS: Array[int] = [{codepoints}]
const ADVANCES: Array[float] = [{advance_text}]
'''
(ROOT / 'systems' / 'ui_font_data.gd').write_text(data, encoding='utf-8')
print(f'Generated {atlas_path.name} + systems/ui_font_data.gd: {len(chars)} glyphs, {atlas.width}x{atlas.height}')
